USE TECHNOBEL;

CREATE TABLE MARQUE(
    ID_MARQUE BIGINT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID_MARQUE)
);

CREATE MODELE(
    ID_MODELE BIGINT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(20) NOT NULL,
    FOREIGN KEY(ID_MARQUE) REFERENCES MARQUE(ID),
    PRIMARY KEY(ID_MODELE)
);
